import { Job, Worker, UnrecoverableError, Queue } from "bullmq";
import { queueConfig } from "../configs/queue.configs";
import { runLLMDebugger } from "../services/llm-debugger.services";
import { logger } from "../utils/logger.utils";

interface DeploymentJobData {
  deploymentId: string;
  vercelPAT: string;
  projectId: string;
}

const redisConfig = {
  host: queueConfig.redis.host,
  port: queueConfig.redis.port,
};

const jobOptions = {
  attempts: 3,
  backoff: { type: "exponential", delay: 5000 },
  removeOnComplete: { count: 100 },
  removeOnFail: { count: 50 },
};

const queue = new Queue(queueConfig.queue3.name, {
  connection: redisConfig,
});

async function fetchDeploymentLogs(
  deploymentId: string,
  vercelPAT: string,
): Promise<{
  logs: string;
  repoName: string;
  owner: string;
  commitSha: string;
  rootDirectory: string | null;
}> {
  const metaRes = await fetch(
    `https://api.vercel.com/v13/deployments/${deploymentId}`,
    {
      headers: { Authorization: `Bearer ${vercelPAT}` },
    },
  );

  if (metaRes.status === 401 || metaRes.status === 403) {
    throw new UnrecoverableError(
      `Vercel auth failed (${metaRes.status}) — check your PAT`,
    );
  }
  if (!metaRes.ok)
    throw new Error(`Vercel Metadata API error: ${metaRes.status}`);
  const metaData = await metaRes.json();

  const res = await fetch(
    `https://api.vercel.com/v3/deployments/${deploymentId}/events`,
    {
      headers: { Authorization: `Bearer ${vercelPAT}` },
    },
  );

  if (res.status === 401 || res.status === 403) {
    throw new UnrecoverableError(
      `Vercel auth failed (${res.status}) — check your PAT`,
    );
  }
  if (!res.ok) {
    throw new Error(`Vercel API error: ${res.status}`);
  }

  const data = await res.json();
  const compiledLogs = data
    .map((event: any) => event.text)
    .filter((text: any) => typeof text === "string" && text.trim() !== "")
    .join("\n");

  return {
    logs: compiledLogs,
    repoName: metaData.meta?.githubRepo || "",
    owner:
      metaData.meta?.githubCommitOrg || metaData.meta?.githubOrg || "iaadi4",
    commitSha: metaData.gitSource?.sha || metaData.meta?.githubCommitSha || "",
    rootDirectory: (metaData.rootDirectory as string | null) ?? null,
  };
}

const worker = new Worker(
  queueConfig.queue1.name,
  async (job: Job<DeploymentJobData>) => {
    const { deploymentId, vercelPAT, projectId } = job.data;

    logger.info(
      { jobId: job.id, deploymentId, attempt: job.attemptsMade + 1 },
      "Job started",
    );

    const result = await fetchDeploymentLogs(deploymentId, vercelPAT);
    if (!result.logs.trim()) {
      logger.warn({ jobId: job.id }, "No logs returned — skipping LLM");
      return;
    }

    const llmOutput = await runLLMDebugger(deploymentId, result.logs);
    logger.info({ jobId: job.id, result }, "Debug result ready");

    const formatSuggestedFixes = (fix: string | string[]): string => {
      const fixes = Array.isArray(fix) ? fix : [fix];
      return fixes.map((f, i) => `${i + 1}. ${f}`).join("\n");
    };

    const formatAffectedFiles = (
      files: typeof llmOutput.affectedFiles,
    ): string => {
      if (!files || files.length === 0)
        return "_No specific files identified._";

      return files
        .map((file) => {
          const location = file.lineNumber ? ` · Line ${file.lineNumber}` : "";
          const snippet = file.snippet
            ? `\n\`\`\`\n${file.snippet}\n\`\`\``
            : "";
          return `- \`${file.filePath}\`${location}${snippet}`;
        })
        .join("\n");
    };

    const confidenceBadge: Record<typeof llmOutput.confidence, string> = {
      high: "🟢 HIGH",
      medium: "🟡 MEDIUM",
      low: "🔴 LOW",
    };

    const refsSection =
      llmOutput.references && llmOutput.references.length > 0
        ? `\n### 🔗 Helpful references\n\n${llmOutput.references.map((ref) => `- [${ref}](${ref})`).join("\n")}\n`
        : "";

    const commentMarkdownBody = `### 🔍 VercelLens build analysis

> **Repo:** \`${result.repoName}\` · **Commit:** \`${result.commitSha.slice(0, 7)}\`

The latest Vercel deployment failed during build.

---

### 📝 Summary

${llmOutput.summary}

### 🚨 Root cause

${llmOutput.rootCause}

---

### 🛠️ Suggested fixes

${formatSuggestedFixes(llmOutput.suggestedFix)}

### 📂 Affected files

${formatAffectedFiles(llmOutput.affectedFiles)}
${refsSection}
---

_Generated by VercelLens · Confidence: ${confidenceBadge[llmOutput.confidence]}_`;

    queue.add(
      "check-docker-build",
      {
        owner: result.owner,
        repo: result.repoName,
        commit_sha: result.commitSha,
        rootDirectory: result.rootDirectory,
        body: commentMarkdownBody,
      },
      jobOptions,
    );
  },
  {
    connection: redisConfig,
    lockDuration: 5 * 60 * 1000,
  },
);

worker.on("failed", (job, err) => {
  logger.error(
    { jobId: job?.id, deploymentId: job?.data?.deploymentId, err: err.message },
    "Job failed",
  );
});

worker.on("completed", (job) => {
  logger.info({ jobId: job.id }, "Job completed");
});