server:
  port: 3000
  env: "development"

ai:
  debugLLMModel: "gemini-2.5-pro"
  filterLLMModel: "gemini-2.5-flash"
  debugLLMProvider: "google-genai"
  filterLLMProvider: "google-genai"

summarize:
  filterThresholdLines: 150
  filterThresholdChars: 6000

secrets:
  geminiApiKey: ""

redis:
  host: "127.0.0.1"
  port: 6379

queue1:
  name: "vercel-log-investigator"

queue2:
  name: "github-pr-bot"

githubApp:
  appId: ""
  privateKey: ""
