server:
  port: 3000
  env: "development"

ai:
  debugLLMModel: "llama-3.3-70b-versatile"
  filterLLMModel: "llama-3.1-8b-instant"
  debugLLMProvider: "groq"
  filterLLMProvider: "groq"

summarize:
  filterThresholdLines: 150
  filterThresholdChars: 6000

secrets:
  groqApiKey: ""

redis:
  host: "127.0.0.1"
  port: 6379

queue1:
  name: "vercel-log-investigator"

queue2:
  name: "github-pr-bot"

githubApp:
  appId: ""
  privateKey: ""
